### ISSUE TITLE
Project Scope Approval

### ISSUE THREAD

**Issue by BradBolander** [wdi-codeninjas/fete#1]
Required: Have instructors approve scope of project. This requires things such as name, wireframes, features, and so forth.

**Comment by code-for-coffee** [comment]
@BradBolander @isaacmabueno I looooove this project! I can't wait to use it! For a stretch goal, here's the Google Calendar 'add event' API: https://developers.google.com/google-apps/calendar/v3/reference/events/insert

Approved!
